version: '3'

services:
  db:
    image: mysql:5.6
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
#    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: weather
    ports:
      - 3306:3306

  servicea:
#    build: .
    image: test-service-a
#    restart: on-failure
    environment:
      WEATHER_HOST: serviceb
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - 8080:8080


  serviceb:
#    build: .
    image: test-service-b
#    restart: on-failure
#    environment:
#      DB_HOST: mysql
#      DB_USER: root
#      DB_PASSWORD: password
#    ports:
#      - 8080:8080